### ISSUE TITLE
Error when connecting to SFTP

### ISSUE THREAD

**Issue by mdelorimier** [lucasmotta/dploy#113]
Hello,

I am having an issue when trying to connect to a SFTP server. This might be linked to the server's fingerprint not beeing known (it is present in ~/.ssh/known_hosts).

Here is the error :

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:161:9)
    at new Buffer (buffer.js:131:17)
    at onNEWKEYS (C:\Users\Mathieu de Lorimier\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Connection.js:2282:29)
    at Parser.<anonymous> (C:\Users\Mathieu de Lorimier\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Connection.js:123:5)
    at emitNone (events.js:105:13)
    at Parser.emit (events.js:207:7)
    at Parser.parsePacket (C:\Users\Mathieu de Lorimier\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Parser.js:468:12)
    at Parser.execute (C:\Users\Mathieu de Lorimier\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Parser.js:249:14)
    at Socket.<anonymous> (C:\Users\Mathieu de Lorimier\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Connection.js:523:18)
    at emitOne (events.js:115:13)
```

And here is the configuration file :

```
stage:
    scheme: sftp
    host: "***.com"
    port: 22
    user: "***"
    pass: "***"
    check: true
    path:
        local: "dist/browser/"
        remote: "public_html/"
```

Regards

**Comment by daywalker2811** [comment]
Hi @mdelorimier 

I'm not an expert in Yaml but I think you should remove the double quotes around values.

Kind regards

**Comment by mdelorimier** [comment]
@daywalker2811 I don't beleive that is the issue : https://stackoverflow.com/a/11301675/643039

**Comment by pegaltier** [comment]
I also encounter problem using sftp

Error log:

[ + ] Fail uploading file site/README.md: { Error: No such file
    at SFTP._parse (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\SFTP\SFTPv3.js:986:23)
    at ChannelStream.<anonymous> (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\SFTP\SFTPv3.js:49:12)
    at emitOne (events.js:116:13)
    at ChannelStream.emit (events.js:211:7)
    at ChannelStream.emit (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Channel.js:640:12)
    at Parser.<anonymous> (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Channel.js:95:20)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.parsePacket (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Parser.js:607:12)
    at Parser.execute (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Parser.js:249:14) type: 'NO_SUCH_FILE', lang: '' }
[ + ] Fail uploading file site/README.md: { Error: No such file
    at SFTP._parse (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\SFTP\SFTPv3.js:986:23)
    at ChannelStream.<anonymous> (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\SFTP\SFTPv3.js:49:12)
    at emitOne (events.js:116:13)
    at ChannelStream.emit (events.js:211:7)
    at ChannelStream.emit (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Channel.js:640:12)
    at Parser.<anonymous> (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Channel.js:95:20)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.parsePacket (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Parser.js:607:12)
    at Parser.execute (C:\Users\pegal\AppData\Roaming\npm\node_modules\dploy\node_modules\ssh2\lib\Parser.js:249:14) type: 'NO_SUCH_FILE', lang: '' }

**Comment by mararn1618** [comment]
Same problem here. SFTP doesn't work.

**version**
```
$ dploy --version
v1.2.0
```

**config**
```
prod:
    scheme: sftp
    port: 21098
    host: 198.54.***.***
    user: *****
    check: true
    include:
        "public/**/*.*": "/"
    path:
        local: public
        remote: /public_html/
```
**error**
```
– Are you sure you want to upload those files? (Y/n) readline.js:1086
            throw err;
            ^
TypeError: Cannot read property 'answer' of undefined
    at C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\lib\deploy.js:578:20
    at C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\prompt\lib\prompt.js:316:20
    at C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\async\lib\async.js:136:21
    at assembler (C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\prompt\lib\prompt.js:282:18) 
    at C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\prompt\lib\prompt.js:322:20
    at C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\prompt\lib\prompt.js:510:14
    at onError (C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\read\lib\read.js:94:12)        
    at Interface.<anonymous> (C:\Users\publi\AppData\Roaming\npm\node_modules\dploy\node_modules\read\lib\read.js:66:5)
    at Interface.emit (events.js:198:13)
    at Interface._ttyWrite (readline.js:801:16)
```
